### ISSUE TITLE
funny

### ISSUE THREAD

**Issue by WebCrew** [GreenVolume/humhub-themes-MadeHub#10]
Hi @Felli 

I started a few weeks ago to use the same base theme for one of my next projects and try to make it more advanced.

The funny and a bit crazy thing with that theme is, that it uses 5 different CSS interpretations (lol). Normal CSS then LESS, SCSS, STYL and SASS :)

Good luck with that theme Sarah ;)

**Comment by Felli** [comment]
Actually this was a test to see which would work better within Humhub themes, which I'm kind of surprised that all of them actually worked pretty well for me. :smiley:

**Comment by WebCrew** [comment]
Yeah You are right it is working as good as perfect. I love that theme because it looks so fresh and new. 

The only thing which is not working are the "_Help&Feedback, Privacy&Terms_" links in the sidebar navigation and also if You create a new page with the Custom Pages module, **no link will be generated in the sidebar navigation**, so we should fix it if You want? 

I think we only have to look for the widget which generates the new links of the Custom Pages module and place it inside the sidebar panel view. 

**Or what do You think?**

Kind regards, Andy

**Comment by Felli** [comment]
You have to add those manually into the `main.php` file under `/themes/MadeHub/views/layouts/main.php` lines 59 to 67 are for the account menu. Because the creator of the theme didn't take into account modules that create pages. lol

**Comment by WebCrew** [comment]
Yes, I know, but what I not know is - do you maybe know what witched we have to use from the Custom Pages module to integrate to main.php to get it working? If not I try to check it out by myself and integrate it ;)

I saw another little issue with the CSS of the Space Chooser Off Canvas panel. I try to fix it too.

**Comment by Felli** [comment]
I'm sure that the answer would be found somewhere in [FlatHub](https://github.com/Felli/humhub-themes-flathub/blob/master/views/layouts/main.php).

**Comment by WebCrew** [comment]
lol yes I think so too :) I also use FlatHub theme often as a example because it seems that Alexandra was one of the less people who had a little understanding for that fucking Yii :)

**Comment by Felli** [comment]
Well the theme did get a 9.27 from Scrutinizer Ci which is pretty good, tho I normally look at the default HubHub theme for better understanding. :+1:

**Comment by WebCrew** [comment]
Do You have the baught version of scrutinizer or the 14 day trial? It is expensive but a good tool.

What do You think about the following style/design? I try to do a HH theme which looks a little like that one: http://demo.rockettheme.com/joomla-templates

**Comment by Felli** [comment]
I'm not into a lot of Joomla's templates, but I will say that I do like the Protean template. As for my [Scrutinizer Ci](https://scrutinizer-ci.com) I'm using the free version at the moment. xD

**Comment by Felli** [comment]
Closing because this has been added noted in #18
